### ISSUE TITLE
Bigscape2 installation error Preparing metadata (pyproject.toml) did not run successfully. get error while installing the bigscape directory 

### ISSUE THREAD

**Issue by PanghalMohit** [medema-group/BiG-SCAPE#230] opened 2024-12-16 06:03 UTC
pip install .
Processing /home/mohit/bigscapelatest/BiG-SCAPE
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
 
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/home/mohit/anaconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/mohit/anaconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/mohit/anaconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-57xcc0rg/overlay/lib/python3.11/site-packages/hatchling/build.py", line 58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-57xcc0rg/overlay/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
          self.metadata.validate_fields()
        File "/tmp/pip-build-env-57xcc0rg/overlay/lib/python3.11/site-packages/hatchling/metadata/core.py", line 265, in validate_fields
          _ = self.version
              ^^^^^^^^^^^^
        File "/tmp/pip-build-env-57xcc0rg/overlay/lib/python3.11/site-packages/hatchling/metadata/core.py", line 149, in version
          self._version = self._get_version()
                          ^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-57xcc0rg/overlay/lib/python3.11/site-packages/hatchling/metadata/core.py", line 260, in _get_version
          raise ValueError(message) from None
      ValueError: Invalid version `release/2.0.0` from field `project.version`, see https://peps.python.org/pep-0440/
      [end of output]
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by adraismawur** [comment] 2024-12-16 08:05
Hi! Thanks for submitting an issue.

We will fix this issue shortly. For now, you should still be able to run BiG-SCAPE by running `python bigscape.py [mode] [arguments]` directly.

**Comment by adraismawur** [comment] 2024-12-16 12:52
Closing as a duplicate of #227. This will be resolved later today.

**Closed by adraismawur** 2024-12-16 12:52 UTC
